name: Upload Beta Release (1GP)
on:
  push:
    branches:    
      - 'main'
jobs:
  upload-beta-release-1gp:
    name: "Upload Beta Release (1GP)"
    environment: packaging
    concurrency: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/release-beta-1gp@main
        with:
          org: '${{ secrets.ORG_JSON }}'
  beta-test:
    name: "Beta Test"
    runs-on: ubuntu-latest
    steps: 
      - uses: cumulusci-actions/beta-test@main
