name: Upload Beta Release (1GP)
on:
  push:
    branches:    
      - 'main'
jobs:
  upload-beta:
    name: "Upload Beta"
    uses: cumulusci-actions/standard-workflows/.github/workflows/beta-1gp.yml@main
    secrets:
      packaging-org-auth-url: '${{ secrets.PACKAGING_AUTH_URL }}'
      dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'
