name: Upload Beta Release
on:
  push:
    branches:    
      - 'main'
jobs:
  upload-release-1gp:
    name: "Upload Release (1GP)"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/release-beta-1gp@main
        with:
          jwt-private-key: '${{ secrets.SERVER_KEY }}'
          connected-app-client-id: '${{ secrets.CLIENT_ID }}'
          username: '${{ secrets.USERNAME }}'
          instance-url: 'https://angellein-labs-dev-ed.my.salesforce.com'
