name: Upload Beta Release (1GP)
on:
  push:
    branches:    
      - 'main'
jobs:
  upload-beta:
    uses: cumulusci-actions/standard-workflows/.github/workflows/beta-1gp.yml@main
    secrets:
      org: '${{ secrets.ORG_JSON }}'
      dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}
