name: Feature Test
on:
  push:
    branches:
      - feature/**
      - main
jobs:
  feature-test:
    name: "Feature Test"
    uses: cumulusci-actions/standard-workflows/.github/workflows/feature-2gp-with-robot.yml@main
    secrets:
      dev-hub-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}
